### PR TITLE
Lab 1

### PR DESCRIPTION
**Pull request by narora4**
Lab 1 completed 
For question 2 I use a Rayleigh distribution and ask the question that what is probability that a point chosen at random is behind the peak value of the distribution. 
And for question 3 I use a poisson distribution and then show but calculating probability of the cumulative probability function whether 'i' number of gamma rays will be detected or not. Proving the question asked that why the mean of a poisson distribution can be 9.2 but not the total number of rays detected in a signal for example 9 or 10.

### CODE REVIEW

**Comment by michaelGRU** [comment]
did you upload a html file? I couldnt find it in your repo

**Comment by oliviatessa** [comment]
@narora4 Please upload an html file of your finished lab. I can't grade until I have the html version.

**Comment by narora4** [comment]
> @narora4 Please upload an html file of your finished lab. I can't grade until I have the html version.

@oliviatessa I just uploaded the html version

**Comment by oliviatessa** [comment]
Overall, your lab needs a lot more explanation. Think of labs as an essay. You are graded primarily on the quality of your explanations and interpretations of your results. Try to write as if to someone who does not have a background in statistics or know what your assignment is until they read your lab. 

There were some parts of the lab you failed to complete, such as the statistical question in part two. This is an important skill and will continue to be important throughout the quarter. 

Also, I think you need to revisit the concept of 'sigma' as a probability. Sigma can be calculated from norminv(). Please look more into this for future labs and ask me questions in lab if you need help understanding the concepts.

**Pull request closed without merging**
